### ISSUE TITLE
Change php files in public to be xyzController 

### ISSUE THREAD

**Issue by pgicking** [PSU-Capstone-2014-B/routelandia-server#19]
I am stupid and keep forgetting what exactly is a controller and whats a model with MVC. Change the file names so that its more explicit. And make sure it doesnt break everything :)

**Comment by severity** [comment]
Attempted to rename the php files in the public folder (Highways, Stations, Detectors) but it changed the URL required to access the data, unless we can figure out a way to make the routing work with the original names and have them point to the correct files this task is not possible.

**Comment by joshproehl** [comment]
Doesn't look like we're going to be able to do this one. Restler appears to need the class name and the file name to match the URL that is going to be used...

So we'll just have to live with remembering that the plural version (Stations) is the controller for the singular entity. (Station)

FYI @pgicking @severity, I'm going to go ahead and close this.
