### ISSUE TITLE
Figure out how to get tests to tests to call their own custom database.

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#33]
Currently the tests run against the API, which means they use whatever database you have configured on your local environment.

This means that running tests will either require that you have a specific database imported, or they will insert and destroy data out of your local database.

This is, in general, bad.
If someone were to run the vendor/bin/behat program while the app was deployed to a production environment this could be WAY WORSE.

Tests should always be run against a clean database with their own fixtures/factories to ensure everything is working correctly. The lack of the ability to do this seriously degrades the usefulness of even having tests, so the joshproehl/bdd branch has been put on hold. 

If we can figure out how to set up tests to run against a clean testing database that they can insert data into then we can move forward with the bdd branch.

**Comment by severity** [comment]
@joshproehl was able to get the BDD testing with behat all setup and i was able to rebase it onto master and everything seems to be working, i have the test database all setup on my local machine and the existing tests @joshproehl wrote have been fixed to work and most everything is passing currently, closing this issue.
