### ISSUE TITLE
OrderedStations entity should have testing

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#4]
Bad Josh, writing code before tests. Fix that crap.

**Comment by joshproehl** [comment]
Blocked by #33
(See also joshproehl/bdd)

**Comment by severity** [comment]
question on this, all of the other testing has been on the input and output of the api, this would be on an entity, how would we go about testing this?

**Comment by severity** [comment]
This is tested by virtue of having tests for the station controller, closing the issue.
