### ISSUE TITLE
getRelatedOnramps() result should be un-pluralized

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#40]
Yeah, this one is my fault. :-)

relatedOnramp being plural was an idea we had as a "just in case", but it appears that this will never happen. Because of this we should un-pluralize the route.

It should be /station/{id}/relatedonramp
And it should return an object with three properties:
stationid: The station requested
calculatedonrampid: The onramp ID calculated
relatedonramp: Either the station for the related onramp, or null if it doesn't exist.

**Comment by joshproehl** [comment]
Assigned to @severity since he's familiar with the code. :-)

**Comment by severity** [comment]
Question: How should we handle the case where someone attempts to get a related onramp id for a station that does not exist? Should we return the 404 from Stations::get when a station doesn't exist or return the object with the station id requested and all of the other fields set to null?

**Comment by joshproehl** [comment]
Answered in #46

**Comment by severity** [comment]
Ok, here is the object that is returned with /stations/1071/relatedOnRamp where 1071 is a station that exists and has an onramp:

  {
    "stationid": 1071,
    "relatedOnrampId": 5071,
    "relatedOnrampInfo": {
        "stationid": 5071,
        "localjurisdiction": 300,
        "controljurisdiction": 300,
        "highwayid": 9,
        "enabledflag": 1,
        "milepost": "6.61",
        "milelog": "6.61",
        "milenumber": "6.61",
        "locationtext": "72nd Ave NB to NB",
        "length": "0",
        "upstream": 0,
        "downstream": 5070,
        "stationclass": 5,
        "segment_odot": 0,
        "numberlanes": 2,
        "gisname": null,
        "smoothingconstant": "0.5",
        "bridginglimit": 3,
        "length_mid": "0",
        "segment": 8,
        "downstream_mile": "0",
        "upstream_mile": "0",
        "agencyid": null,
        "opposite_stationid": null,
        "segment_raw": null,
        "segment_50k": null,
        "segment_100k": null,
        "segment_250k": null,
        "segment_500k": null,
        "segment_1000k": null,
        "point": null
    }
}

**Comment by severity** [comment]
Here is the output when /stations/3177/relatedOnRamp is used where 3177 is a station that exists but has no onramp:

  {
    "error": {
        "code": 404,
        "message": "Not Found: No Onramps were found."
    },
    "debug": {
        "source": "Stations.php:71 at call stage",
        "stages": {
            "success": [
                "get",
                "route",
                "negotiate",
                "validate"
            ],
            "failure": [
                "call",
                "message"
            ]
        }
    }
}

**Comment by severity** [comment]
Here is the output when /stations/1081/relatedOnRamp is used where 1081 is a station that does not exist:

  {
    "error": {
        "code": 404,
        "message": "Not Found: Could not find the stationID requested"
    },
    "debug": {
        "source": "OrderedStation.php:130 at call stage",
        "stages": {
            "success": [
                "get",
                "route",
                "negotiate",
                "validate"
            ],
            "failure": [
                "call",
                "message"
            ]
        }
    }
}

**Comment by severity** [comment]
are we happy with that? :D

**Comment by pgicking** [comment]
hell yea

**Comment by joshproehl** [comment]
Actually....
If the station IS found, but the related onramp is NOT found, then the relatedOnramp object should be null... 

Once again, back to the object-oriented thinking: You got a station object, so there's no error thrown, but the method you called on IT just returns null... Since we're returning information about the station itself (i.e. it's ID and what the calculated relatedOnrampID was...) we should actually return that, but indicate that there simply wasn't a related onramp object...

**Comment by severity** [comment]
Ok, so right now if it tries to find an onramp that doesn't exist, the station class throws an exception, should i have the "relatedOnrampInfo": field just be the words 'null' or should i put in a string like 'No Onramps Detected: Reticulating Splines' or something ;)

**Comment by joshproehl** [comment]
Part of the JSON spec (json.org) defines the possible datatypes... string, number, etc... null is one of them. No quotes, it's not a STRING that says null, it IS a null.

Now, how to get Restler to do that?
I suspect if you assign the field in the return value to null instead of the relatedOnramp object it should do the trick.

**Comment by severity** [comment]
Good?

  {
    "stationid": 3177,
    "relatedOnrampId": 5177,
    "relatedOnrampInfo": null
}

**Comment by joshproehl** [comment]
:+1:

**Comment by severity** [comment]
issue resolved, closing.
