### ISSUE TITLE
Move testing data for statistics query to staging server

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#44]
We need some testing data for the statistics query.

What we need:
- The loopdata tables for the entire last week of January (ending today the 30th)
- Loopdata tables for the previous 6 fridays preceding today. (Total of 7 fridays worth of data)

We also need to pull data out of the large aggregated table, but let's do that as a second project as it's not going to be a straightforward table dump.

**Comment by pgicking** [comment]
done, left the loopback tables .sql files in my public directory (/home/pgicking/Public) incase we have to redump.
