### ISSUE TITLE
stations/{id}/relatedonramps gives wrong response

### ISSUE THREAD

**Issue by severity** [PSU-Capstone-2014-B/routelandia-server#46]
when going to http://capstoneaa.cs.pdx.edu/api/stations/1 you get the following response:
{
    "error": {
        "code": 404,
        "message": "Not Found: Could not find the stationID requested"
blahblahblah.

however, when going to stations/1/relatedonramps, or any other station that does not exist, it shows the following:
{
    "stationid": 1,
    "relatedOnrampId": null,
    "relatedOnramps": [
        {
            "stationid": 1091,
            "localjurisdiction": 300,
            "controljurisdiction": 300,
            "highwayid": 11,
            "enabledflag": 1,
            "milepost": "71.37",
            "milelog": "71.37",
            "milenumber": "71.37",
            "locationtext": "Skyline Rd EB",
            "length": "0.63",
            "upstream": 1090,
            "downstream": 3161,
            "stationclass": 1,
            "segment_odot": 0,
            "numberlanes": 3,
            "gisname": "-122.7392:45.50745:-122.72497:45.50823",
            "smoothingconstant": "0.5",
            "bridginglimit": 3,
            "length_mid": null,
            "segment": null,
            "downstream_mile": null,
            "upstream_mile": null,
            "agencyid": "141",
            "opposite_stationid": null,
            "segment_raw": "0102000020110F000017000000705blah
            "segment_50k": blahblah and so on....

i believe when looking up a related onramp for a station that does not exist, when the "relatedOnrampId" is null, we shouldn't be outputting any station information at all. I'm not sure if we should throw a 404 or just politely reply that the station does not exist and neither does any related onramp.

**Comment by pgicking** [comment]
I remember also noticing this when I was making error handling. I think it should throw an error when the station doesn't exist. 

The [fetchRelatedOnRamp in orderedstation](https://github.com/PSU-Capstone-2014-B/routelandia-server/blob/master/entities/OrderedStation.php#L164) is the only database call that doesn't check for any errors. Thats probably where this is happening.

**Comment by severity** [comment]
Actually i think it is the getRelatedOnramps method in stations.php, it just creates an object and starts jamming it with data, not checking it AT ALL. Of course I wrote it, ha ha, I am in the middle of changing it to non-plural and posted a question about how to handle the non-existent station in #40 , this issue is a bit redundant in retrospect :)

**Comment by pgicking** [comment]
Oh haha, ill leave it to you then

**Comment by severity** [comment]
I could use some input though, how should we handle checking if a non-existent station has an onramp? Should we throw an exception or return an object with the requested station id and all other fields set to null? I'm just not sure what would be the best way to handle this

**Comment by pgicking** [comment]
I'd lean towards throwing an exception when the station doesn't exist. Since it always returns the same onramp station when the station doesn't exist, I dont think this is one of those cases where returning nothing is still valid like it was with the highways.

**Comment by severity** [comment]
Ok, that sounds good, i could use the get method in stations in a try catch block and just catch and throw the exception if the station doesn't exist, how does that sound?

**Comment by pgicking** [comment]
Its worth a shot :)

**Comment by severity** [comment]
cool, i'll work on it tonight after work :)

**Comment by joshproehl** [comment]
:+1:  for throwing an exception when the station doesn't exist.

Think of how most programming languages handle this... You're essentially trying to call a method on a null object. That's definitely an error.

**Comment by severity** [comment]
issue resolved, closing
