### ISSUE TITLE
Stations controller should have tests

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#5]
Bad josh, writing code without tests. Needs fixing.

**Comment by joshproehl** [comment]
Stubbed in joshproehl/bdd
Blocked by #33

**Comment by severity** [comment]
@joshproehl has written some tests for the stations controller and all but one of the tests are currently passing, #46 was opened in response to the test that was not passing. At this point i'm not sure if the tests we have are enough or if we need more, and if we should wait to close this issue until we think we are done writing tests.

**Comment by severity** [comment]
Once the creating tests branch is added to master this issue can be closed :)

**Comment by severity** [comment]
testing branch has been merged to master, closing this issue :)
