### ISSUE TITLE
Error message returned when matching stations could not be found should include the start and end stations lists.

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#57]
In order to help debug data issues the list of start stations and end stations that were used when attempting to find a linked-list between the two.

Ideally these would be returned NOT as part of the text message error, but as part of the JSON structure of the error, so that they can be programatically parsed by the client app. However as a starting point putting them in the text message of the error would be fine.

**Comment by pgicking** [comment]
Just to document, in my branch I have messages move up the call stack instead of just defaulting too "u bad at highways" so that should help debugging. It will also tell us when PostGIS cant find a nearby coordinate with a specific (but ugly looking) error message. 

Also the list of stations will be returned if there are no matching highways between them. This coordinate tuple will demonstrate

```bash
curl -X POST http://localhost:8080/api/trafficstats -H "Content-Type: application/json" -d '
{
    "startpt": {
       "lat": 45.608105591041,
       "lng": -122.68130608198        },
    "endpt": {
       "lat": 45.530059536306,
       "lng":  -122.61469439568
    },
    "time": {
       "midpoint": "17:30",
       "weekday": "Thursday"
    }
}
';
echo "Startpoint is stationid: 1026 highwayid: 2";
echo "EndPoint is Stationid: 3130 highwayid: 7"
```

**Comment by pgicking** [comment]
```
{
    "error": {
        "code": 400,
        "message": "Bad Request: Given coordinates refer to stations on different highways. Start Stations: 1024,1025,1026,1027 End Stations: 1057,1061,3130,3176,1057,1061,3130,3176,1057,1061,3130,3176,1057,1061,3130,3176"
    },
    "debug": {
        "source": "TrafficStats.php:80 at call stage",
        "stages": {
            "success": [
                "get",
                "route",
                "negotiate",
                "validate"
            ],
            "failure": [
                "call",
                "message"
            ]
        }
    }
}
```

**Comment by pgicking** [comment]
With merging of StationsPairingTuning, this is fixed
