### ISSUE TITLE
Add documentation about testing to README

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#61]
Add a section to the README.md file for testing, explaining how to set up and use the tests that we have.

**Comment by severity** [comment]
working on this now, I found the script for creating the highwayshavingstations view but haven't found one for orderedstations, does anyone know where it is documented?

**Comment by severity** [comment]
This is done, just needs to be reviewed and merged :D

**Comment by joshproehl** [comment]
Closed by #67 which has been merged.
