### ISSUE TITLE
Switch the returned coordinates in station linestrings

### ISSUE THREAD

**Issue by pgicking** [PSU-Capstone-2014-B/routelandia-server#63]
Its currently -122 then 45, it should be 45 then -122

**Comment by joshproehl** [comment]
Mind changed. Per discussion with @pgicking this appears to be an issue in PostGis. (It should be returning points in EPSG:4326's lat/lng order)

The only *good* solution would be to take the points apart in PHP and put them into individual "lat:" and "lng:" fields in the JSON, and that's a parsing overhead we just don't want to introduce. We'll leave them as is.
