### ISSUE TITLE
Times sent to the backend should be rounded to the nearest 15 minutes

### ISSUE THREAD

**Issue by severity** [PSU-Capstone-2014-B/routelandia-server#68]
When a request is sent to the backend from the android app, the time received should be rounded to the nearest 15 minute interval to avoid problems

**Comment by joshproehl** [comment]
We should get this done pre-deployment. Assigning to @pgicking.

**Comment by pgicking** [comment]
Done, waiting on PR :)

**Comment by severity** [comment]
PR Granted :)
issue has been resolved, closing...
