### ISSUE TITLE
Investigate making staging server automatically run migrations.sql automatically during deployments.

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#7]
Ideally would only do so if one of the changed files was migrations.sql

**Comment by pgicking** [comment]
What tool on the staging server is updating from the github currently?

**Comment by joshproehl** [comment]
Currently there's a github webhook (in the project settings) that calls a URL on the staging server. This URL is a php page that parses the JSON that github sends as the payload of the hook, and then dispatches a shell script that calls a git pull. 

This is very fragile, but so far it works.

My cheap-and-dirty idea for updating was to have the shell script automatically pipe the migrations.sql into psql or something like that. Once again, it's fragile, dirty, and sort of dangerous. Not something you'd want to do for a production deployment, but for the purpose of the next 6 weeks I wouldn't be *terribly* worried about it.

**Comment by joshproehl** [comment]
No further schema changes anticipated, so this won't be needed... And since our staging server will be taken down right after the quarter is over no point in making long term solutions...
