### ISSUE TITLE
All API results should be wrapped into a results object

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#76]
Instead of simply returning JSON Arrays of results, every API result returned should be an object. The results of the query/request/etc sholud be in an array called "results" in this object.

This will allow us to return additional fields, such as "debug", or other arbitrary info, without interfering with API Client's ability to handle results.

```json
{
  "results":[]
}
```

Additionally, existing API routes  that return a single object should return that object as the single element in the results array.
Example:
```json
{
  "results":[
    {"singleResultFieldOne":1, "singleResultFieldTwo":99}
  ]
}
```

This allows API clients to always look at the results field, and always know it will be an array, then handle each element OF the array as a unique object. This makes for easier parsing, and happier clients!

**Comment by joshproehl** [comment]
@severity I know you already started on the first part, so I'm assigning this to you... But I can't remember if I told you about wrapping single result objects to make the "results" always an array... :smiley:

**Comment by severity** [comment]
@joshproehl i've implemented it, for some of the api urls, the original output was an array, so for example, http://localhost/api/highways/ has a results field with an array that holds an array of highways:
{
    "results": [
        [
            {
                "highwayid": 1,
                "direction": "NORTH ",
                "highwayname": "I-5                 ",
                "bound": "NB"
            },
is that acceptable?

**Comment by severity** [comment]
lol, never mind, now it will throw the output into an array called results if the object is not an array, otherwise it just puts the output into the results field, doh

**Comment by severity** [comment]
this done, pull requested and ready to be merged :)
