### ISSUE TITLE
Move the require of database.php into the index.php file

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#8]
It should be included once, so that each controller file doesn't have to include it manually. (Every controller will read it.)

**Comment by severity** [comment]
Do I need to go into the controller files and remove the require to database.php references in addition or just add the require to the index.php file?

**Comment by joshproehl** [comment]
The goal is to put it somewhere that it doesn't have to get required in Highways.php, Stations.php, and any new controller php files that go in the public folder.

Since every controller is called *by* the index.php file, it seems to me that putting the require_once for database into that index file should mean that it's already included everywhere it's needed, and should be able to be removed from the other files. (If it can be removed, this is a way to ensure that new files created won't *need* to include it.)

**Comment by severity** [comment]
Sure, I just figured the database.php file was already referenced in Highways.php and would need to  be removed once it is referenced in index.php, i wasn't sure if those other references would need to be removed or not

**Comment by joshproehl** [comment]
the idea is to make it only referenced once, yep!  (Thus the title "move". :-D)

**Comment by severity** [comment]
ok, right now it is only referenced in highways.php, stations.php and detectors.php, got it, i will remove them :)

**Comment by severity** [comment]
finished, pushed it up and submitted a pull request :)
