### ISSUE TITLE
convert RelatedOnrampId to RelatedOnramp

### ISSUE THREAD

**Issue by joshproehl** [PSU-Capstone-2014-B/routelandia-server#9]
Rather than the api returning a non-json route showing just the relatedonrampID, there should be a relatedOnramp route (/api/stations/1064/relatedonramp) which returns the following json object:

```
{
  stationid: integer ID of the station being requested,
  relatedOnrampId: calculated integer ID of the related onramp,
  relatedOnramps: [ array of related onramps ]
}
```

Currently only one related onramp will be calculated or returned, but using the array as the structure allows for future expansion, and makes it logical to understand the returned json structure.

**Comment by severity** [comment]
ok, dumb question time, this would be replacing the getRelatedOnrampId route(function/method) with a route called relatedOnramp that would output a json object as described above, in the stations.php file?

**Comment by joshproehl** [comment]
That's the idea! Creating the object may provide a little challenge, AND you'll need to keep (or re-implement) the logic in the existing method to calculate the ID.)

**Comment by severity** [comment]
ok, im looking at the code for getForHighway above it, would I approach this the same way or similarly? Also, is decodeSegmentsJson something created/defined for this particular program/server thing we are developing or is it an established json command?

**Comment by joshproehl** [comment]
for decodeSegmentsJson() take a look at the OrderedStation.php entity. (And there are 2 issues open related to how it needs to be removed.)

And yeah, there are some similarities to getForHighway, but it's not quite exactly the same...

Take it step by step. Make a method at the new URL you want, then make it return just the related ID, then make it return some kind of object that contains the related ID *AND* the requested ID (as shown above in the example JSON. Watch out though, there's no example of how to do this!) then figure out how to determine if the relatedonramp exists.
